### ISSUE TITLE
 To edit the README.md doc

### ISSUE THREAD

**Issue by Desgard** [HackSwjtu/HackSwjtu.github.io#8]
We need to tell everyone the technologies about our page.
There are some key words: **Jekyll**, **Gitpage**, **markdown**. And you need to introduce these in `README.md`.
So if you want to write it better, you must learn `markdown` file, and its mark words.

**Comment by Desgard** [comment]
First you need to `clone` the master branch of our page. 

``` bash
git clone git@github.com:HackSwjtu/HackSwjtu.github.io.git
```

And then, to edit the `README.md`, it will show in the index of our repo.

You can learn `markdown` mark language from: [马克飞象](https://maxiang.io/). And you need to learn about `Jekyll` static page generator technology from [https://jekyllrb.com/](https://jekyllrb.com/)

**Comment by g1ave** [comment]
Roger.

**Comment by Desgard** [comment]
The beautiful `README.md` is just like [this](https://github.com/robbyrussell/oh-my-zsh). You can try to imitate them.
